seed_everything: 42

trainer:
  max_epochs: 10
  accelerator: cpu
  devices: 1
  log_every_n_steps: 1
  profiler: simple
  precision: 32-true
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: .
      name: logs

model:
  model_config:
    fc_out:
      latlng: 64
      others: 32
    latent_dim: 128
    scale_factor: 1.0
    features: 128
    extraction_dim: 128
    use_transformer:
      generator: true
      discriminator: true
    transformer:
      kernel_size: 16
      num_heads: 8
      num_layers: 3
      num_embeddings: 512
      dropout: 0.1
      feedforward:
        feedforward_dim: 256
        dropout: 0.1
      attention:
        attention_type: entmax15
        dropout: 0.2
  optimizers:
    learning_rate: 0.0001
    betas: [0.5, 0.999]
  criterions:
    alpha: 1.0
    beta: 10.0
    gamma: 1.0

data:
  dm_config:
    data_dir: data/Geolife/Data
    ind_dir: data/Geoind/Data
    batch_size: 8
    length_range: [32, 2048]
    ratio: [0.8, 0.2]
    num_workers: 6

ckpt_path: null
